<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('courses')->insert([
            /* fase 1 */
            [
                'name'              => 'creatie 1',
                'slug'              => 'creatie-1',
                'course_code'       => 'YP0583',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '9',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'code 1',
                'slug'              => 'code-1',
                'course_code'       => 'YP0584',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '12',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Communicatie 1',
                'slug'              => 'communicatie-1',
                'course_code'       => 'YP0585',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Entrepreneurship 1',
                'slug'              => 'Entrepreneurship-1',
                'course_code'       => 'YP0593',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Ontwerpen 1',
                'slug'              => 'Ontwerpen-1',
                'course_code'       => 'YP0586',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Code 2',
                'slug'              => 'Code-2',
                'course_code'       => 'YP0587',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Smart technology 1',
                'slug'              => 'Smart-technology-1',
                'course_code'       => 'YP0503',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Communicatie 2',
                'slug'              => 'Communicatie-2',
                'course_code'       => 'YP0442',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Lab 1',
                'slug'              => 'Lab-1',
                'course_code'       => 'YP0588',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '12',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            /* fase 2 */
            [
                'name'              => 'Ontwerpen 2',
                'slug'              => 'Ontwerpen-2',
                'course_code'       => 'YP0629',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '9',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'creatie 2',
                'slug'              => 'creatie-2',
                'course_code'       => 'YP0534',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Communicatie 3',
                'slug'              => 'Communicatie-3',
                'course_code'       => 'YP0535',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Code 3',
                'slug'              => 'Code-3',
                'course_code'       => 'YP0630',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '9',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Smart technology 2',
                'slug'              => 'Smart-technology-2',
                'course_code'       => 'YP0537',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Lab 2',
                'slug'              => 'Lab-2',
                'course_code'       => 'YP0631',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '12',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Entrepreneurship 2',
                'slug'              => 'Entrepreneurship-2',
                'course_code'       => 'YP0632',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            /* choice fase 2 */
            [
                'name'              => 'Playground 1',
                'slug'              => 'Playground-1',
                'course_code'       => 'YP0977',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'International Playground 1',
                'slug'              => 'International-Playground-1',
                'course_code'       => 'YP1005',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Playground 2',
                'slug'              => 'Playground-2',
                'course_code'       => 'YP0978',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'International Playground 2',
                'slug'              => 'International-Playground-2',
                'course_code'       => 'YP1006',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Webtech 3',
                'slug'              => 'Webtech-3',
                'course_code'       => 'YP0506',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Visualisatie',
                'slug'              => 'Visualisatie',
                'course_code'       => 'YP0541',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            /* fase 3 */
            [
                'name'              => 'Personal Branding',
                'slug'              => 'Personal-branding',
                'course_code'       => 'YP0505',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Entrepreneurship 3',
                'slug'              => 'Entrepreneurship-3',
                'course_code'       => 'YP0633',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Communicatie 4',
                'slug'              => 'Communicatie-4',
                'course_code'       => 'YP0206',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Ethiek',
                'slug'              => 'Ethiek',
                'course_code'       => 'YP0207',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Stage',
                'slug'              => 'Stage',
                'course_code'       => 'YP0529',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '15',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Lab 3',
                'slug'              => 'Lab-3',
                'course_code'       => 'YP0634',
                'semester'          => 'images/secondsem.png',
                'studyPoints'       => '15',
                'obligated'         => 'yes',
                'educations_id'     => '1',
            ],
            /* choice fase 3 */
            [
                'name'              => 'Advanced Webtech Back',
                'slug'              => 'Advanced-Webtech-Back',
                'course_code'       => 'YP0589',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'CMS module en templates',
                'slug'              => 'CMS-module-en-templates',
                'course_code'       => 'YP0591',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Visual Branding',
                'slug'              => 'Visual-branding',
                'course_code'       => 'YP0218',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Mobile Design',
                'slug'              => 'Mobile-Design',
                'course_code'       => 'YP0453',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            /* choice fase 2&3 */
            [
                'name'              => 'Mobile Development',
                'slug'              => 'Mobile-Development',
                'course_code'       => 'YP0539',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'ASP.NET',
                'slug'              => 'ASP.NET',
                'course_code'       => 'YP0509',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Mobile Devolopment Scripting',
                'slug'              => 'Mobile-Devolopment-Scripting',
                'course_code'       => 'YP0590',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Trendwatching',
                'slug'              => 'Trendwatching',
                'course_code'       => 'YP0221',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Interface Development for Designers',
                'slug'              => 'Interface-Development-for-Designers',
                'course_code'       => 'YP0540',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Digitaal Magazine',
                'slug'              => 'Digitaal-Magazine',
                'course_code'       => 'YP0513',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '3',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],
            [
                'name'              => 'Virtual Reality/360',
                'slug'              => 'Virtual-Reality/360',
                'course_code'       => 'YP0592',
                'semester'          => 'images/firstsem.png',
                'studyPoints'       => '6',
                'obligated'         => 'no',
                'educations_id'     => '1',
            ],


        ]);
    }
}
